// This file is generated by Tools/generate_route_ledger.py. Do not edit.
// Source: pinned Moby Engine Swagger specifications for API 1.44 through 1.53.

import ContainerEngineWire

public enum DockerEngineAPIRouteLedger {
    public static let minimumAPIVersion = try! DockerAPIVersion("1.44")
    public static let maximumAPIVersion = try! DockerAPIVersion("1.53")
    public static let routeCount = 107

    public static let sources: [DockerRouteLedgerSource] = [
        DockerRouteLedgerSource(
            apiVersion: "1.44",
            revision: "v25.0.0",
            sha256: "8e33e8c83f4963535e624de923776e41aa5c3b827c2afb6c1b9ece4e461d9345"
        ),
        DockerRouteLedgerSource(
            apiVersion: "1.45",
            revision: "v26.0.0",
            sha256: "08a57910580acc947376bf7ad96fa3993a2f3483bc0f31a69bd374daccff20be"
        ),
        DockerRouteLedgerSource(
            apiVersion: "1.46",
            revision: "v27.0.1",
            sha256: "6c9afa985a92bee15c378f4d6e53bda5e845542cfb3d27ac054c1e0a272a4628"
        ),
        DockerRouteLedgerSource(
            apiVersion: "1.47",
            revision: "v27.2.0",
            sha256: "12003d071b594bb93c30528f1b23faa23b4047bf77d7330c23667989ff84a036"
        ),
        DockerRouteLedgerSource(
            apiVersion: "1.48",
            revision: "v28.0.0",
            sha256: "f8ab34e2c9af2613b2cebb3f27d6552b8cc06decad7dd30e2adddd2d8c3c4376"
        ),
        DockerRouteLedgerSource(
            apiVersion: "1.49",
            revision: "v28.1.0",
            sha256: "f56f003a4e9790e5e645096c1fa8f97d129f42311c22e59df4c47fb0a9c7aa6d"
        ),
        DockerRouteLedgerSource(
            apiVersion: "1.50",
            revision: "v28.2.0",
            sha256: "3a78a994dd0d65886987793aa4fc4b5b7fa0b1d050cc926dabf454c685a6ba4f"
        ),
        DockerRouteLedgerSource(
            apiVersion: "1.51",
            revision: "v28.3.0",
            sha256: "61bb32ec005ff02acd818b90e20510c957f1ed0fc11e9701f0b2f5f3d93e3b0b"
        ),
        DockerRouteLedgerSource(
            apiVersion: "1.52",
            revision: "docker-v29.0.0",
            sha256: "69fe12ce2c6ef1e42a317e5c3d60c9e0dbc5bf4f30e56472ab947975d9a6eedb"
        ),
        DockerRouteLedgerSource(
            apiVersion: "1.53",
            revision: "docker-v29.2.1",
            sha256: "b5c86ad3803a4e0843659ddedb2fc35f62c398342c2dcc5ebbc153ab40ec3318"
        )
    ]

    public static func make(
        implementedRouteIdentifiers: Set<String> = []
    ) throws -> DockerRouteLedger {
        try DockerRouteLedger(
            minimumAPIVersion: minimumAPIVersion,
            maximumAPIVersion: maximumAPIVersion,
            routes: [
                DockerRouteMetadata(
                    identifier: "ContainerList",
                    method: .get,
                    pattern: DockerRoutePattern("/containers/json"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("ContainerList") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "ContainerCreate",
                    method: .post,
                    pattern: DockerRoutePattern("/containers/create"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("ContainerCreate") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "ContainerInspect",
                    method: .get,
                    pattern: DockerRoutePattern("/containers/{id}/json"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("ContainerInspect") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "ContainerTop",
                    method: .get,
                    pattern: DockerRoutePattern("/containers/{id}/top"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("ContainerTop") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "ContainerLogs",
                    method: .get,
                    pattern: DockerRoutePattern("/containers/{id}/logs"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .stream,
                    disposition: implementedRouteIdentifiers.contains("ContainerLogs") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "ContainerChanges",
                    method: .get,
                    pattern: DockerRoutePattern("/containers/{id}/changes"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("ContainerChanges") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "ContainerExport",
                    method: .get,
                    pattern: DockerRoutePattern("/containers/{id}/export"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .stream,
                    disposition: implementedRouteIdentifiers.contains("ContainerExport") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "ContainerStats",
                    method: .get,
                    pattern: DockerRoutePattern("/containers/{id}/stats"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .stream,
                    disposition: implementedRouteIdentifiers.contains("ContainerStats") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "ContainerResize",
                    method: .post,
                    pattern: DockerRoutePattern("/containers/{id}/resize"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("ContainerResize") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "ContainerStart",
                    method: .post,
                    pattern: DockerRoutePattern("/containers/{id}/start"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("ContainerStart") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "ContainerStop",
                    method: .post,
                    pattern: DockerRoutePattern("/containers/{id}/stop"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("ContainerStop") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "ContainerRestart",
                    method: .post,
                    pattern: DockerRoutePattern("/containers/{id}/restart"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("ContainerRestart") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "ContainerKill",
                    method: .post,
                    pattern: DockerRoutePattern("/containers/{id}/kill"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("ContainerKill") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "ContainerUpdate",
                    method: .post,
                    pattern: DockerRoutePattern("/containers/{id}/update"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("ContainerUpdate") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "ContainerRename",
                    method: .post,
                    pattern: DockerRoutePattern("/containers/{id}/rename"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("ContainerRename") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "ContainerPause",
                    method: .post,
                    pattern: DockerRoutePattern("/containers/{id}/pause"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("ContainerPause") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "ContainerUnpause",
                    method: .post,
                    pattern: DockerRoutePattern("/containers/{id}/unpause"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("ContainerUnpause") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "ContainerAttach",
                    method: .post,
                    pattern: DockerRoutePattern("/containers/{id}/attach"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .hijack,
                    disposition: implementedRouteIdentifiers.contains("ContainerAttach") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "ContainerAttachWebsocket",
                    method: .get,
                    pattern: DockerRoutePattern("/containers/{id}/attach/ws"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .hijack,
                    disposition: implementedRouteIdentifiers.contains("ContainerAttachWebsocket") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "ContainerWait",
                    method: .post,
                    pattern: DockerRoutePattern("/containers/{id}/wait"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("ContainerWait") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "ContainerDelete",
                    method: .delete,
                    pattern: DockerRoutePattern("/containers/{id}"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("ContainerDelete") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "ContainerArchiveInfo",
                    method: .head,
                    pattern: DockerRoutePattern("/containers/{id}/archive"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("ContainerArchiveInfo") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "ContainerArchive",
                    method: .get,
                    pattern: DockerRoutePattern("/containers/{id}/archive"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .stream,
                    disposition: implementedRouteIdentifiers.contains("ContainerArchive") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "PutContainerArchive",
                    method: .put,
                    pattern: DockerRoutePattern("/containers/{id}/archive"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("PutContainerArchive") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "ContainerPrune",
                    method: .post,
                    pattern: DockerRoutePattern("/containers/prune"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("ContainerPrune") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "ImageList",
                    method: .get,
                    pattern: DockerRoutePattern("/images/json"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("ImageList") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "ImageBuild",
                    method: .post,
                    pattern: DockerRoutePattern("/build"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .stream,
                    disposition: implementedRouteIdentifiers.contains("ImageBuild") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "BuildPrune",
                    method: .post,
                    pattern: DockerRoutePattern("/build/prune"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .stream,
                    disposition: implementedRouteIdentifiers.contains("BuildPrune") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "ImageCreate",
                    method: .post,
                    pattern: DockerRoutePattern("/images/create"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .stream,
                    disposition: implementedRouteIdentifiers.contains("ImageCreate") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "ImageInspect",
                    method: .get,
                    pattern: DockerRoutePattern("/images/{name...}/json"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("ImageInspect") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "ImageHistory",
                    method: .get,
                    pattern: DockerRoutePattern("/images/{name...}/history"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("ImageHistory") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "ImagePush",
                    method: .post,
                    pattern: DockerRoutePattern("/images/{name...}/push"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .stream,
                    disposition: implementedRouteIdentifiers.contains("ImagePush") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "ImageTag",
                    method: .post,
                    pattern: DockerRoutePattern("/images/{name...}/tag"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("ImageTag") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "ImageDelete",
                    method: .delete,
                    pattern: DockerRoutePattern("/images/{name...}"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("ImageDelete") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "ImageSearch",
                    method: .get,
                    pattern: DockerRoutePattern("/images/search"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("ImageSearch") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "ImagePrune",
                    method: .post,
                    pattern: DockerRoutePattern("/images/prune"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("ImagePrune") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "SystemAuth",
                    method: .post,
                    pattern: DockerRoutePattern("/auth"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("SystemAuth") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "SystemInfo",
                    method: .get,
                    pattern: DockerRoutePattern("/info"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("SystemInfo") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "SystemVersion",
                    method: .get,
                    pattern: DockerRoutePattern("/version"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("SystemVersion") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "SystemPing",
                    method: .get,
                    pattern: DockerRoutePattern("/_ping"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("SystemPing") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "SystemPingHead",
                    method: .head,
                    pattern: DockerRoutePattern("/_ping"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("SystemPingHead") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "ImageCommit",
                    method: .post,
                    pattern: DockerRoutePattern("/commit"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("ImageCommit") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "SystemEvents",
                    method: .get,
                    pattern: DockerRoutePattern("/events"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .stream,
                    disposition: implementedRouteIdentifiers.contains("SystemEvents") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "SystemDataUsage",
                    method: .get,
                    pattern: DockerRoutePattern("/system/df"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("SystemDataUsage") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "ImageGet",
                    method: .get,
                    pattern: DockerRoutePattern("/images/{name...}/get"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .stream,
                    disposition: implementedRouteIdentifiers.contains("ImageGet") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "ImageGetAll",
                    method: .get,
                    pattern: DockerRoutePattern("/images/get"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .stream,
                    disposition: implementedRouteIdentifiers.contains("ImageGetAll") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "ImageLoad",
                    method: .post,
                    pattern: DockerRoutePattern("/images/load"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .stream,
                    disposition: implementedRouteIdentifiers.contains("ImageLoad") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "ContainerExec",
                    method: .post,
                    pattern: DockerRoutePattern("/containers/{id}/exec"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("ContainerExec") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "ExecStart",
                    method: .post,
                    pattern: DockerRoutePattern("/exec/{id}/start"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .hijack,
                    disposition: implementedRouteIdentifiers.contains("ExecStart") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "ExecResize",
                    method: .post,
                    pattern: DockerRoutePattern("/exec/{id}/resize"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("ExecResize") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "ExecInspect",
                    method: .get,
                    pattern: DockerRoutePattern("/exec/{id}/json"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("ExecInspect") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "VolumeList",
                    method: .get,
                    pattern: DockerRoutePattern("/volumes"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("VolumeList") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "VolumeCreate",
                    method: .post,
                    pattern: DockerRoutePattern("/volumes/create"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("VolumeCreate") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "VolumeInspect",
                    method: .get,
                    pattern: DockerRoutePattern("/volumes/{name}"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("VolumeInspect") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "VolumeUpdate",
                    method: .put,
                    pattern: DockerRoutePattern("/volumes/{name}"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("VolumeUpdate") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "VolumeDelete",
                    method: .delete,
                    pattern: DockerRoutePattern("/volumes/{name}"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("VolumeDelete") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "VolumePrune",
                    method: .post,
                    pattern: DockerRoutePattern("/volumes/prune"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("VolumePrune") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "NetworkList",
                    method: .get,
                    pattern: DockerRoutePattern("/networks"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("NetworkList") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "NetworkInspect",
                    method: .get,
                    pattern: DockerRoutePattern("/networks/{id}"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("NetworkInspect") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "NetworkDelete",
                    method: .delete,
                    pattern: DockerRoutePattern("/networks/{id}"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("NetworkDelete") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "NetworkCreate",
                    method: .post,
                    pattern: DockerRoutePattern("/networks/create"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("NetworkCreate") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "NetworkConnect",
                    method: .post,
                    pattern: DockerRoutePattern("/networks/{id}/connect"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("NetworkConnect") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "NetworkDisconnect",
                    method: .post,
                    pattern: DockerRoutePattern("/networks/{id}/disconnect"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("NetworkDisconnect") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "NetworkPrune",
                    method: .post,
                    pattern: DockerRoutePattern("/networks/prune"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("NetworkPrune") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "PluginList",
                    method: .get,
                    pattern: DockerRoutePattern("/plugins"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("PluginList") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "GetPluginPrivileges",
                    method: .get,
                    pattern: DockerRoutePattern("/plugins/privileges"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("GetPluginPrivileges") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "PluginPull",
                    method: .post,
                    pattern: DockerRoutePattern("/plugins/pull"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("PluginPull") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "PluginInspect",
                    method: .get,
                    pattern: DockerRoutePattern("/plugins/{name}/json"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("PluginInspect") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "PluginDelete",
                    method: .delete,
                    pattern: DockerRoutePattern("/plugins/{name}"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("PluginDelete") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "PluginEnable",
                    method: .post,
                    pattern: DockerRoutePattern("/plugins/{name}/enable"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("PluginEnable") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "PluginDisable",
                    method: .post,
                    pattern: DockerRoutePattern("/plugins/{name}/disable"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("PluginDisable") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "PluginUpgrade",
                    method: .post,
                    pattern: DockerRoutePattern("/plugins/{name}/upgrade"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("PluginUpgrade") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "PluginCreate",
                    method: .post,
                    pattern: DockerRoutePattern("/plugins/create"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("PluginCreate") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "PluginPush",
                    method: .post,
                    pattern: DockerRoutePattern("/plugins/{name}/push"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("PluginPush") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "PluginSet",
                    method: .post,
                    pattern: DockerRoutePattern("/plugins/{name}/set"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("PluginSet") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "NodeList",
                    method: .get,
                    pattern: DockerRoutePattern("/nodes"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: .platformUnavailable
                ),
                DockerRouteMetadata(
                    identifier: "NodeInspect",
                    method: .get,
                    pattern: DockerRoutePattern("/nodes/{id}"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: .platformUnavailable
                ),
                DockerRouteMetadata(
                    identifier: "NodeDelete",
                    method: .delete,
                    pattern: DockerRoutePattern("/nodes/{id}"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: .platformUnavailable
                ),
                DockerRouteMetadata(
                    identifier: "NodeUpdate",
                    method: .post,
                    pattern: DockerRoutePattern("/nodes/{id}/update"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: .platformUnavailable
                ),
                DockerRouteMetadata(
                    identifier: "SwarmInspect",
                    method: .get,
                    pattern: DockerRoutePattern("/swarm"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: .platformUnavailable
                ),
                DockerRouteMetadata(
                    identifier: "SwarmInit",
                    method: .post,
                    pattern: DockerRoutePattern("/swarm/init"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: .platformUnavailable
                ),
                DockerRouteMetadata(
                    identifier: "SwarmJoin",
                    method: .post,
                    pattern: DockerRoutePattern("/swarm/join"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: .platformUnavailable
                ),
                DockerRouteMetadata(
                    identifier: "SwarmLeave",
                    method: .post,
                    pattern: DockerRoutePattern("/swarm/leave"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: .platformUnavailable
                ),
                DockerRouteMetadata(
                    identifier: "SwarmUpdate",
                    method: .post,
                    pattern: DockerRoutePattern("/swarm/update"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: .platformUnavailable
                ),
                DockerRouteMetadata(
                    identifier: "SwarmUnlockkey",
                    method: .get,
                    pattern: DockerRoutePattern("/swarm/unlockkey"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: .platformUnavailable
                ),
                DockerRouteMetadata(
                    identifier: "SwarmUnlock",
                    method: .post,
                    pattern: DockerRoutePattern("/swarm/unlock"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: .platformUnavailable
                ),
                DockerRouteMetadata(
                    identifier: "ServiceList",
                    method: .get,
                    pattern: DockerRoutePattern("/services"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: .platformUnavailable
                ),
                DockerRouteMetadata(
                    identifier: "ServiceCreate",
                    method: .post,
                    pattern: DockerRoutePattern("/services/create"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: .platformUnavailable
                ),
                DockerRouteMetadata(
                    identifier: "ServiceInspect",
                    method: .get,
                    pattern: DockerRoutePattern("/services/{id}"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: .platformUnavailable
                ),
                DockerRouteMetadata(
                    identifier: "ServiceDelete",
                    method: .delete,
                    pattern: DockerRoutePattern("/services/{id}"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: .platformUnavailable
                ),
                DockerRouteMetadata(
                    identifier: "ServiceUpdate",
                    method: .post,
                    pattern: DockerRoutePattern("/services/{id}/update"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: .platformUnavailable
                ),
                DockerRouteMetadata(
                    identifier: "ServiceLogs",
                    method: .get,
                    pattern: DockerRoutePattern("/services/{id}/logs"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .stream,
                    disposition: .platformUnavailable
                ),
                DockerRouteMetadata(
                    identifier: "TaskList",
                    method: .get,
                    pattern: DockerRoutePattern("/tasks"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: .platformUnavailable
                ),
                DockerRouteMetadata(
                    identifier: "TaskInspect",
                    method: .get,
                    pattern: DockerRoutePattern("/tasks/{id}"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: .platformUnavailable
                ),
                DockerRouteMetadata(
                    identifier: "TaskLogs",
                    method: .get,
                    pattern: DockerRoutePattern("/tasks/{id}/logs"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .stream,
                    disposition: .platformUnavailable
                ),
                DockerRouteMetadata(
                    identifier: "SecretList",
                    method: .get,
                    pattern: DockerRoutePattern("/secrets"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: .platformUnavailable
                ),
                DockerRouteMetadata(
                    identifier: "SecretCreate",
                    method: .post,
                    pattern: DockerRoutePattern("/secrets/create"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: .platformUnavailable
                ),
                DockerRouteMetadata(
                    identifier: "SecretInspect",
                    method: .get,
                    pattern: DockerRoutePattern("/secrets/{id}"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: .platformUnavailable
                ),
                DockerRouteMetadata(
                    identifier: "SecretDelete",
                    method: .delete,
                    pattern: DockerRoutePattern("/secrets/{id}"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: .platformUnavailable
                ),
                DockerRouteMetadata(
                    identifier: "SecretUpdate",
                    method: .post,
                    pattern: DockerRoutePattern("/secrets/{id}/update"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: .platformUnavailable
                ),
                DockerRouteMetadata(
                    identifier: "ConfigList",
                    method: .get,
                    pattern: DockerRoutePattern("/configs"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: .platformUnavailable
                ),
                DockerRouteMetadata(
                    identifier: "ConfigCreate",
                    method: .post,
                    pattern: DockerRoutePattern("/configs/create"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: .platformUnavailable
                ),
                DockerRouteMetadata(
                    identifier: "ConfigInspect",
                    method: .get,
                    pattern: DockerRoutePattern("/configs/{id}"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: .platformUnavailable
                ),
                DockerRouteMetadata(
                    identifier: "ConfigDelete",
                    method: .delete,
                    pattern: DockerRoutePattern("/configs/{id}"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: .platformUnavailable
                ),
                DockerRouteMetadata(
                    identifier: "ConfigUpdate",
                    method: .post,
                    pattern: DockerRoutePattern("/configs/{id}/update"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: .platformUnavailable
                ),
                DockerRouteMetadata(
                    identifier: "DistributionInspect",
                    method: .get,
                    pattern: DockerRoutePattern("/distribution/{name}/json"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .bytes,
                    disposition: implementedRouteIdentifiers.contains("DistributionInspect") ? .implemented : .unimplemented
                ),
                DockerRouteMetadata(
                    identifier: "Session",
                    method: .post,
                    pattern: DockerRoutePattern("/session"),
                    introduced: DockerAPIVersion("1.44"),
                    responseMode: .hijack,
                    disposition: implementedRouteIdentifiers.contains("Session") ? .implemented : .unimplemented
                )
            ]
        )
    }
}
