sonar.projectKey=stephenlclarke_container-engine-api
sonar.organization=stephenlclarke
sonar.projectName=container-engine-api
sonar.host.url=https://sonarcloud.io
sonar.sourceEncoding=UTF-8
sonar.sources=Sources
sonar.tests=Tests
sonar.exclusions=**/.build/**,**/*.pb.swift,**/*.grpc.swift
sonar.test.inclusions=Tests/**/*.swift
