# Copyright 2026 container-engine-api project authors. SPDX-License-Identifier: Apache-2.0
load("@rules_shell//shell:sh_binary.bzl", "sh_binary")
exports_files(["rules-license-empty-provider.patch", "rules-swift-sandbox-output.patch"])
sh_binary(
    name = "ssd_test_runner", srcs = ["ssd-test-runner.sh"], visibility = ["//visibility:public"],
)
