#!/usr/bin/env python3
"""Generate the Docker Engine API 1.53 route ledger from pinned Moby specs."""

from __future__ import annotations

import argparse
import hashlib
import pathlib
import re
import tempfile
import urllib.request
from dataclasses import dataclass


ROOT = pathlib.Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = (
    ROOT
    / "Sources"
    / "ContainerEngineRouter"
    / "DockerEngineAPIRouteLedger.generated.swift"
)


@dataclass(frozen=True)
class Source:
    version: str
    revision: str
    sha256: str


SOURCES = (
    Source("1.44", "v25.0.0", "8e33e8c83f4963535e624de923776e41aa5c3b827c2afb6c1b9ece4e461d9345"),
    Source("1.45", "v26.0.0", "08a57910580acc947376bf7ad96fa3993a2f3483bc0f31a69bd374daccff20be"),
    Source("1.46", "v27.0.1", "6c9afa985a92bee15c378f4d6e53bda5e845542cfb3d27ac054c1e0a272a4628"),
    Source("1.47", "v27.2.0", "12003d071b594bb93c30528f1b23faa23b4047bf77d7330c23667989ff84a036"),
    Source("1.48", "v28.0.0", "f8ab34e2c9af2613b2cebb3f27d6552b8cc06decad7dd30e2adddd2d8c3c4376"),
    Source("1.49", "v28.1.0", "f56f003a4e9790e5e645096c1fa8f97d129f42311c22e59df4c47fb0a9c7aa6d"),
    Source("1.50", "v28.2.0", "3a78a994dd0d65886987793aa4fc4b5b7fa0b1d050cc926dabf454c685a6ba4f"),
    Source("1.51", "v28.3.0", "61bb32ec005ff02acd818b90e20510c957f1ed0fc11e9701f0b2f5f3d93e3b0b"),
    Source("1.52", "docker-v29.0.0", "69fe12ce2c6ef1e42a317e5c3d60c9e0dbc5bf4f30e56472ab947975d9a6eedb"),
    Source("1.53", "docker-v29.2.1", "b5c86ad3803a4e0843659ddedb2fc35f62c398342c2dcc5ebbc153ab40ec3318"),
)

METHODS = {"delete", "get", "head", "post", "put"}
STREAM_OPERATIONS = {
    "BuildPrune",
    "ContainerArchive",
    "ContainerExport",
    "ContainerLogs",
    "ContainerStats",
    "ImageBuild",
    "ImageCreate",
    "ImageGet",
    "ImageGetAll",
    "ImageLoad",
    "ImagePush",
    "ServiceLogs",
    "SystemEvents",
    "TaskLogs",
}
HIJACK_OPERATIONS = {
    "ContainerAttach",
    "ContainerAttachWebsocket",
    "ExecStart",
    "Session",
}
PLATFORM_UNAVAILABLE_PREFIXES = (
    "/configs",
    "/nodes",
    "/secrets",
    "/services",
    "/swarm",
    "/tasks",
)


@dataclass(frozen=True)
class Route:
    method: str
    path: str
    operation: str

    @property
    def signature(self) -> tuple[str, str]:
        return self.method, self.path


def download(source: Source, directory: pathlib.Path) -> pathlib.Path:
    destination = directory / f"docker-engine-api-{source.version}.yaml"
    url = (
        "https://raw.githubusercontent.com/moby/moby/"
        f"{source.revision}/api/swagger.yaml"
    )
    with urllib.request.urlopen(url, timeout=30) as response:
        payload = response.read()
    digest = hashlib.sha256(payload).hexdigest()
    if digest != source.sha256:
        raise SystemExit(
            f"{source.version} digest mismatch: expected {source.sha256}, got {digest}"
        )
    destination.write_bytes(payload)
    return destination


def parse_routes(specification: pathlib.Path) -> list[Route]:
    path: str | None = None
    method: str | None = None
    routes: list[Route] = []
    for line in specification.read_text(encoding="utf-8").splitlines():
        path_match = re.fullmatch(r"  (/\S+):", line)
        if path_match:
            path = path_match.group(1)
            method = None
            continue
        method_match = re.fullmatch(r"    ([a-z]+):", line)
        if method_match and method_match.group(1) in METHODS:
            method = method_match.group(1)
            continue
        operation_match = re.fullmatch(r'      operationId: "([A-Za-z0-9]+)"', line)
        if operation_match and path is not None and method is not None:
            routes.append(Route(method, path, operation_match.group(1)))
            method = None

    signatures = [route.signature for route in routes]
    operations = [route.operation for route in routes]
    if len(signatures) != len(set(signatures)):
        raise SystemExit(f"duplicate method/path in {specification}")
    if len(operations) != len(set(operations)):
        raise SystemExit(f"duplicate operationId in {specification}")
    return routes


def swift_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def router_path(value: str) -> str:
    """Allow Docker image names to retain unescaped registry path segments."""
    return value.replace("/images/{name}", "/images/{name...}")


def response_mode(operation: str) -> str:
    if operation in HIJACK_OPERATIONS:
        return ".hijack"
    if operation in STREAM_OPERATIONS:
        return ".stream"
    return ".bytes"


def render(specifications: list[pathlib.Path]) -> str:
    versions = [parse_routes(path) for path in specifications]
    available = [{route.signature for route in routes} for routes in versions]
    current = versions[-1]
    lines = [
        "// This file is generated by Tools/generate_route_ledger.py. Do not edit.",
        "// Source: pinned Moby Engine Swagger specifications for API 1.44 through 1.53.",
        "",
        "import ContainerEngineWire",
        "",
        "public enum DockerEngineAPIRouteLedger {",
        "    public static let minimumAPIVersion = try! DockerAPIVersion(\"1.44\")",
        "    public static let maximumAPIVersion = try! DockerAPIVersion(\"1.53\")",
        f"    public static let routeCount = {len(current)}",
        "",
        "    public static let sources: [DockerRouteLedgerSource] = [",
    ]
    for index, source in enumerate(SOURCES):
        lines.extend(
            [
                "        DockerRouteLedgerSource(",
                f'            apiVersion: "{source.version}",',
                f'            revision: "{source.revision}",',
                f'            sha256: "{source.sha256}"',
                "        )" + ("," if index + 1 < len(SOURCES) else ""),
            ]
        )
    lines.extend(
        [
            "    ]",
            "",
            "    public static func make(",
            "        implementedRouteIdentifiers: Set<String> = []",
            "    ) throws -> DockerRouteLedger {",
            "        try DockerRouteLedger(",
            "            minimumAPIVersion: minimumAPIVersion,",
            "            maximumAPIVersion: maximumAPIVersion,",
            "            routes: [",
        ]
    )
    for route_index, route in enumerate(current):
        introduced_index = next(
            index for index, signatures in enumerate(available) if route.signature in signatures
        )
        disposition = (
            ".platformUnavailable"
            if route.path.startswith(PLATFORM_UNAVAILABLE_PREFIXES)
            else "implementedRouteIdentifiers.contains(\"%s\") ? .implemented : .unimplemented"
            % swift_string(route.operation)
        )
        lines.extend(
            [
                "                DockerRouteMetadata(",
                f'                    identifier: "{swift_string(route.operation)}",',
                f"                    method: .{route.method},",
                f'                    pattern: DockerRoutePattern("{swift_string(router_path(route.path))}"),',
                f'                    introduced: DockerAPIVersion("{SOURCES[introduced_index].version}"),',
                f"                    responseMode: {response_mode(route.operation)},",
                f"                    disposition: {disposition}",
                "                )" + ("," if route_index + 1 < len(current) else ""),
            ]
        )
    lines.extend(["            ]", "        )", "    }", "}", ""])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=pathlib.Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the checked-in generated source is stale",
    )
    arguments = parser.parse_args()
    with tempfile.TemporaryDirectory(prefix="container-engine-route-ledger-") as value:
        directory = pathlib.Path(value)
        generated = render([download(source, directory) for source in SOURCES])
    if arguments.check:
        current = arguments.output.read_text(encoding="utf-8")
        if current != generated:
            raise SystemExit(f"generated route ledger is stale: {arguments.output}")
        return
    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    arguments.output.write_text(generated, encoding="utf-8")


if __name__ == "__main__":
    main()
